steps:
  # Deploy the source to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:534.0.0'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      # Deploy directly from source
      - '--source=.'
      - '--region=$_REGION'
      - '--platform=managed'
      - '--port=8080'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE_NAME: r-mobile-blog
  _REGION: us-central1