steps:
  # Build the Next.js application image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '--tag=gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA'
      - '--target=runner'
      - '.'

  # Deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdk/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image=gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA'
      - '--region=$_REGION'
      - '--platform=managed'
      - '--port=8080'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE_NAME: r-mobile-blog
  _REGION: us-central1